package moscow.rockstar.systems.modules.modules.other.autobuy;

import net.minecraft.component.DataComponentTypes;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.text.Text;
import java.util.ArrayList;
import java.util.List;

public final class AutoBuyCatalog {
    private AutoBuyCatalog() {}

    public static List<AutoBuyItem> defaults() {
        List<AutoBuyItem> items = new ArrayList<>();
        add(items, "HolyWorld", "holyworld_шлем_infinity_netherite_helmet", "Шлем Infinity", Items.NETHERITE_HELMET, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_нагрудник_infinity_netherite_chestplate", "Нагрудник Infinity", Items.NETHERITE_CHESTPLATE, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_поножи_infinity_netherite_leggings", "Поножи Infinity", Items.NETHERITE_LEGGINGS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_ботинки_infinity_netherite_boots", "Ботинки Infinity", Items.NETHERITE_BOOTS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_шлем_eternity_netherite_helmet", "Шлем Eternity", Items.NETHERITE_HELMET, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_нагрудник_eternity_netherite_chestplate", "Нагрудник Eternity", Items.NETHERITE_CHESTPLATE, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_штаны_eternity_netherite_leggings", "Штаны Eternity", Items.NETHERITE_LEGGINGS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_ботинки_eternity_netherite_boots", "Ботинки Eternity", Items.NETHERITE_BOOTS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_шлем_солнца_golden_helmet", "Шлем солнца", Items.GOLDEN_HELMET, AutoBuyCategory.ARMOR, 100000L);
        add(items, "HolyWorld", "holyworld_броневая_элитра_elytra", "Броневая элитра", Items.ELYTRA, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_элитры_elytra", "Элитры", Items.ELYTRA, AutoBuyCategory.ARMOR, 500000L);
        add(items, "HolyWorld", "holyworld_меч_eternity_netherite_sword", "Меч Eternity", Items.NETHERITE_SWORD, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "HolyWorld", "holyworld_меч_infinity_netherite_sword", "Меч Infinity", Items.NETHERITE_SWORD, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "HolyWorld", "holyworld_кирка_eternity_netherite_pickaxe", "Кирка Eternity", Items.NETHERITE_PICKAXE, AutoBuyCategory.TOOLS, 500000L);
        add(items, "HolyWorld", "holyworld_арбалет_eternity_crossbow", "Арбалет Eternity", Items.CROSSBOW, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "HolyWorld", "holyworld_громовержец_trident", "Громовержец", Items.TRIDENT, AutoBuyCategory.WEAPONS, 100000L);
        add(items, "HolyWorld", "holyworld_тотем_бессмертия_totem_of_undying", "Тотем бессмертия", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 80000L);
        add(items, "HolyWorld", "holyworld_зачарованное_золотое_яблоко_enchanted_golden_apple", "Зачарованное золотое яблоко", Items.ENCHANTED_GOLDEN_APPLE, AutoBuyCategory.FOOD, 150000L);
        add(items, "HolyWorld", "holyworld_золотое_яблоко_golden_apple", "Золотое яблоко", Items.GOLDEN_APPLE, AutoBuyCategory.FOOD, 100000L);
        add(items, "HolyWorld", "holyworld_золотая_морковь_golden_carrot", "Золотая морковь", Items.GOLDEN_CARROT, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_эндер_жемчуг_ender_pearl", "Эндер жемчуг", Items.ENDER_PEARL, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_плод_хоруса_chorus_fruit", "Плод хоруса", Items.CHORUS_FRUIT, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_осколочное_яйцо_pufferfish_spawn_egg", "Осколочное яйцо", Items.PUFFERFISH_SPAWN_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_осколочное_эндер_яйцо_enderman_spawn_egg", "Осколочное эндер яйцо", Items.ENDERMAN_SPAWN_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_яйцо_дракона_dragon_egg", "Яйцо Дракона", Items.DRAGON_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_золотой_спавнер_spawner", "Золотой Спавнер", Items.SPAWNER, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "HolyWorld", "holyworld_фейерверк_firework_rocket", "Фейерверк", Items.FIREWORK_ROCKET, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_незеритовый_слиток_netherite_ingot", "Незеритовый слиток", Items.NETHERITE_INGOT, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_порох_gunpowder", "Порох", Items.GUNPOWDER, AutoBuyCategory.MISC, 100000L);
        add(items, "HolyWorld", "holyworld_боевой_фрагмент_prismarine_crystals", "Боевой фрагмент", Items.PRISMARINE_CRYSTALS, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_шлем_крушителя_netherite_helmet", "Шлем Крушителя", Items.NETHERITE_HELMET, AutoBuyCategory.ARMOR, 500000L);
        add(items, "SpookyTime", "spookytime_нагрудник_крушителя_netherite_chestplate", "Нагрудник Крушителя", Items.NETHERITE_CHESTPLATE, AutoBuyCategory.ARMOR, 500000L);
        add(items, "SpookyTime", "spookytime_поножи_крушителя_netherite_leggings", "Поножи Крушителя", Items.NETHERITE_LEGGINGS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "SpookyTime", "spookytime_ботинки_крушителя_netherite_boots", "Ботинки Крушителя", Items.NETHERITE_BOOTS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "SpookyTime", "spookytime_меч_крушителя_netherite_sword", "Меч Крушителя", Items.NETHERITE_SWORD, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "SpookyTime", "spookytime_трезубец_крушителя_trident", "Трезубец Крушителя", Items.TRIDENT, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "SpookyTime", "spookytime_арбалет_крушителя_crossbow", "Арбалет Крушителя", Items.CROSSBOW, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "SpookyTime", "spookytime_кирка_крушителя_netherite_pickaxe", "Кирка Крушителя", Items.NETHERITE_PICKAXE, AutoBuyCategory.TOOLS, 500000L);
        add(items, "SpookyTime", "spookytime_элитры_крушителя_elytra", "Элитры Крушителя", Items.ELYTRA, AutoBuyCategory.ARMOR, 500000L);
        add(items, "SpookyTime", "spookytime_талисман_карателя_totem_of_undying", "Талисман Карателя", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "SpookyTime", "spookytime_талисман_крушителя_totem_of_undying", "Талисман Крушителя", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 500000L);
        add(items, "SpookyTime", "spookytime_талисман_раздора_totem_of_undying", "Талисман Раздора", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "SpookyTime", "spookytime_талисман_тирана_totem_of_undying", "Талисман Тирана", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "SpookyTime", "spookytime_талисман_ярости_totem_of_undying", "Талисман Ярости", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "SpookyTime", "spookytime_талисман_вихря_totem_of_undying", "Талисман Вихря", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "SpookyTime", "spookytime_талисман_мрака_totem_of_undying", "Талисман Мрака", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "SpookyTime", "spookytime_талисман_демона_totem_of_undying", "Талисман Демона", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "SpookyTime", "spookytime_тотем_бессмертия_totem_of_undying", "Тотем бессмертия", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 80000L);
        add(items, "SpookyTime", "spookytime_пузыр_к_опыта_experience_bottle", "Пузырёк опыта", Items.EXPERIENCE_BOTTLE, AutoBuyCategory.EXPERIENCE, 2000L);
        add(items, "SpookyTime", "spookytime_чарка_enchanted_golden_apple", "Чарка", Items.ENCHANTED_GOLDEN_APPLE, AutoBuyCategory.FOOD, 150000L);
        add(items, "SpookyTime", "spookytime_золотое_яблоко_golden_apple", "Золотое яблоко", Items.GOLDEN_APPLE, AutoBuyCategory.FOOD, 100000L);
        add(items, "SpookyTime", "spookytime_яблоко_apple", "Яблоко", Items.APPLE, AutoBuyCategory.FOOD, 100000L);
        add(items, "SpookyTime", "spookytime_перка_ender_pearl", "Перка", Items.ENDER_PEARL, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_незеритовый_слиток_netherite_ingot", "Незеритовый слиток", Items.NETHERITE_INGOT, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_незеритовый_лом_netherite_scrap", "Незеритовый лом", Items.NETHERITE_SCRAP, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_алмаз_diamond", "Алмаз", Items.DIAMOND, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_изумруд_emerald", "Изумруд", Items.EMERALD, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_золотой_слиток_gold_ingot", "Золотой слиток", Items.GOLD_INGOT, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_алмазный_блок_diamond_block", "Алмазный блок", Items.DIAMOND_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_изумрудный_блок_emerald_block", "Изумрудный блок", Items.EMERALD_BLOCK, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_золотой_блок_gold_block", "Золотой блок", Items.GOLD_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_обсидиан_obsidian", "Обсидиан", Items.OBSIDIAN, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_голова_дракона_dragon_head", "Голова дракона", Items.DRAGON_HEAD, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_голова_визер_скелета_wither_skeleton_skull", "Голова визер-скелета", Items.WITHER_SKELETON_SKULL, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_древние_обломки_ancient_debris", "Древние обломки", Items.ANCIENT_DEBRIS, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_яйцо_призыва_крестьянина_villager_spawn_egg", "Яйцо призыва крестьянина", Items.VILLAGER_SPAWN_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_яйцо_зомби_крестьянина_zombie_villager_spawn_egg", "Яйцо зомби-крестьянина", Items.ZOMBIE_VILLAGER_SPAWN_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_элитры_elytra", "Элитры", Items.ELYTRA, AutoBuyCategory.ARMOR, 500000L);
        add(items, "SpookyTime", "spookytime_золотая_морковь_golden_carrot", "Золотая морковь", Items.GOLDEN_CARROT, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_шалкер_shulker_box", "Шалкер", Items.SHULKER_BOX, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_маяк_beacon", "Маяк", Items.BEACON, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_алмазная_руда_diamond_ore", "Алмазная руда", Items.DIAMOND_ORE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_изумрудная_руда_emerald_ore", "Изумрудная руда", Items.EMERALD_ORE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_спавнер_spawner", "Спавнер", Items.SPAWNER, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "SpookyTime", "spookytime_порох_gunpowder", "Порох", Items.GUNPOWDER, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_книга_починка_enchanted_book", "Книга починка", Items.ENCHANTED_BOOK, AutoBuyCategory.MISC, 100000L);
        add(items, "SpookyTime", "spookytime_динамит_tnt", "Динамит", Items.TNT, AutoBuyCategory.BLOCKS, 5000L);
        add(items, "FunTime", "funtime_золотое_яблоко_golden_apple", "Золотое яблоко", Items.GOLDEN_APPLE, AutoBuyCategory.FOOD, 100000L);
        add(items, "FunTime", "funtime_зачарованное_золотое_яблоко_enchanted_golden_apple", "Зачарованное золотое яблоко", Items.ENCHANTED_GOLDEN_APPLE, AutoBuyCategory.FOOD, 150000L);
        add(items, "FunTime", "funtime_порох_gunpowder", "Порох", Items.GUNPOWDER, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_бирка_name_tag", "Бирка", Items.NAME_TAG, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_трезубец_trident", "Трезубец", Items.TRIDENT, AutoBuyCategory.WEAPONS, 100000L);
        add(items, "FunTime", "funtime_незеритовый_слиток_netherite_ingot", "Незеритовый слиток", Items.NETHERITE_INGOT, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_алмаз_diamond", "Алмаз", Items.DIAMOND, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_алмазный_блок_diamond_block", "Алмазный блок", Items.DIAMOND_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_золотой_слиток_gold_ingot", "Золотой слиток", Items.GOLD_INGOT, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_блок_золота_gold_block", "Блок золота", Items.GOLD_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_маяк_beacon", "Маяк", Items.BEACON, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_пузыр_к_опыта_experience_bottle", "Пузырёк опыта", Items.EXPERIENCE_BOTTLE, AutoBuyCategory.EXPERIENCE, 2000L);
        add(items, "FunTime", "funtime_звезда_незера_nether_star", "Звезда Незера", Items.NETHER_STAR, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_шалкеровый_ящик_shulker_box", "Шалкеровый ящик", Items.SHULKER_BOX, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_железный_слиток_iron_ingot", "Железный слиток", Items.IRON_INGOT, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_железный_блок_iron_block", "Железный блок", Items.IRON_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_незеритовый_блок_netherite_block", "Незеритовый блок", Items.NETHERITE_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_спавнер_spawner", "Спавнер", Items.SPAWNER, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_элитры_elytra", "Элитры", Items.ELYTRA, AutoBuyCategory.ARMOR, 500000L);
        add(items, "FunTime", "funtime_эндер_жемчуг_ender_pearl", "Эндер жемчуг", Items.ENDER_PEARL, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_обсидиан_obsidian", "Обсидиан", Items.OBSIDIAN, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_тотем_бессмертия_totem_of_undying", "Тотем бессмертия", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 80000L);
        add(items, "FunTime", "funtime_палка_ифрита_blaze_rod", "Палка ифрита", Items.BLAZE_ROD, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_динамит_tnt", "Динамит", Items.TNT, AutoBuyCategory.BLOCKS, 5000L);
        add(items, "FunTime", "funtime_яйцо_зомби_жителя_zombie_villager_spawn_egg", "Яйцо зомби-жителя", Items.ZOMBIE_VILLAGER_SPAWN_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_голова_дракона_dragon_head", "Голова дракона", Items.DRAGON_HEAD, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_алмазная_руда_diamond_ore", "Алмазная руда", Items.DIAMOND_ORE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_изумрудная_руда_emerald_ore", "Изумрудная руда", Items.EMERALD_ORE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_яблоко_apple", "Яблоко", Items.APPLE, AutoBuyCategory.FOOD, 100000L);
        add(items, "FunTime", "funtime_торт_cake", "Торт", Items.CAKE, AutoBuyCategory.FOOD, 100000L);
        add(items, "FunTime", "funtime_фейерверк_firework_rocket", "Фейерверк", Items.FIREWORK_ROCKET, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_яйцо_жителя_villager_spawn_egg", "Яйцо жителя", Items.VILLAGER_SPAWN_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_яйцо_вихря_breeze_spawn_egg", "Яйцо вихря", Items.BREEZE_SPAWN_EGG, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_мешок_bundle", "Мешок", Items.BUNDLE, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_булава_mace", "Булава", Items.MACE, AutoBuyCategory.WEAPONS, 100000L);
        add(items, "FunTime", "funtime_незеритовое_улучшение_netherite_upgrade_smithing_template", "Незеритовое улучшение", Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE, AutoBuyCategory.TOOLS, 100000L);
        add(items, "FunTime", "funtime_tnt_tier_white_tnt", "TNT - TIER WHITE", Items.TNT, AutoBuyCategory.BLOCKS, 5000L);
        add(items, "FunTime", "funtime_tnt_tier_black_tnt", "TNT - TIER BLACK", Items.TNT, AutoBuyCategory.BLOCKS, 5000L);
        add(items, "FunTime", "funtime_голова_скелета_skeleton_skull", "Голова скелета", Items.SKELETON_SKULL, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_голова_зомби_zombie_head", "Голова зомби", Items.ZOMBIE_HEAD, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_голова_крипера_creeper_head", "Голова крипера", Items.CREEPER_HEAD, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_голова_визер_скелета_wither_skeleton_skull", "Голова визер-скелета", Items.WITHER_SKELETON_SKULL, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_голова_пиглина_piglin_head", "Голова пиглина", Items.PIGLIN_HEAD, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_зловещий_ключ_испытаний_ominous_trial_key", "Зловещий ключ испытаний", Items.OMINOUS_TRIAL_KEY, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_ключ_испытаний_trial_key", "Ключ испытаний", Items.TRIAL_KEY, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_заряд_ветра_wind_charge", "Заряд ветра", Items.WIND_CHARGE, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_стержень_вихря_breeze_rod", "Стержень вихря", Items.BREEZE_ROD, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_талисман_раздора_totem_of_undying", "[★] Талисман Раздора", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_карателя_totem_of_undying", "[★] Талисман Карателя", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_крушителя_totem_of_undying", "Талисман Крушителя", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 500000L);
        add(items, "FunTime", "funtime_талисман_тирана_totem_of_undying", "[★] Талисман Тирана", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_ярости_totem_of_undying", "[★] Талисман Ярости", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_демона_totem_of_undying", "[★] Талисман Демона", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_вихря_totem_of_undying", "[★] Талисман Вихря", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_мрака_totem_of_undying", "[★] Талисман Мрака", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_сфера_хаоса_player_head", "[★] Сфера Хаоса", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_сатира_player_head", "[★] Сфера Сатира", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_бестии_player_head", "[★] Сфера Бестии", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_ареса_player_head", "[★] Сфера Ареса", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_гидры_player_head", "[★] Сфера Гидры", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_икара_player_head", "[★] Сфера Икара", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_эрида_player_head", "[★] Сфера Эрида", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_афины_player_head", "[★] Сфера Афины", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_святая_вода_splash_potion", "[★] Святая вода", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_гнева_splash_potion", "[★] Зелье Гнева", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_палладина_splash_potion", "[★] Зелье Палладина", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_ассасина_splash_potion", "[★] Зелье Ассасина", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_радиации_splash_potion", "[★] Зелье Радиации", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_снотворное_splash_potion", "[★] Снотворное", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_явная_пыль_sugar", "[★] Явная пыль", Items.SUGAR, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_дезориентация_ender_eye", "[★] Дезориентация", Items.ENDER_EYE, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_трапка_netherite_scrap", "[★] Трапка", Items.NETHERITE_SCRAP, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_отмычка_к_сферам_tripwire_hook", "Отмычка к Сферам", Items.TRIPWIRE_HOOK, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_пласт_dried_kelp", "[★] Пласт", Items.DRIED_KELP, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_пузырек_опыта_15_ур_experience_bottle", "Пузырек опыта [15 ур]", Items.EXPERIENCE_BOTTLE, AutoBuyCategory.EXPERIENCE, 2000L);
        add(items, "FunTime", "funtime_пузыр_к_опыта_30_ур_experience_bottle", "Пузырёк опыта [30 Ур.]", Items.EXPERIENCE_BOTTLE, AutoBuyCategory.EXPERIENCE, 2000L);
        add(items, "FunTime", "funtime_пузырек_опыта_50_ур_experience_bottle", "Пузырек опыта [50 ур]", Items.EXPERIENCE_BOTTLE, AutoBuyCategory.EXPERIENCE, 2000L);
        add(items, "FunTime", "funtime_tnt_tier_white_tnt", "[★] TNT - TIER WHITE", Items.TNT, AutoBuyCategory.BLOCKS, 5000L);
        add(items, "FunTime", "funtime_tnt_tier_black_tnt", "[★] TNT - TIER BLACK", Items.TNT, AutoBuyCategory.BLOCKS, 5000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_случайный_campfire", "Сигнальный огонь [Случайный]", Items.CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_обычный_campfire", "Сигнальный огонь [Обычный]", Items.CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_богатый_campfire", "Сигнальный огонь [Богатый]", Items.CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_легендарный_campfire", "Сигнальный огонь [Легендарный]", Items.CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_блок_дамагер_jigsaw", "[★] Блок дамагер", Items.JIGSAW, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_прогрузчик_чанков_1x1_structure_block", "Прогрузчик чанков [1x1]", Items.STRUCTURE_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_прогрузчик_чанков_3x3_structure_block", "Прогрузчик чанков [3x3]", Items.STRUCTURE_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_прогрузчик_чанков_5x5_structure_block", "Прогрузчик чанков [5x5]", Items.STRUCTURE_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_загадочный_маяк_beacon", "Загадочный маяк", Items.BEACON, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_проклятая_душа_soul_lantern", "[★] Проклятая душа", Items.SOUL_LANTERN, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_драконий_скин_paper", "[★] Драконий скин", Items.PAPER, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_огненный_смерч_fire_charge", "[★] Огненный смерч", Items.FIRE_CHARGE, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_снежок_заморозка_snowball", "[★] Снежок заморозка", Items.SNOWBALL, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_божья_аура_phantom_membrane", "[★] Божья аура", Items.PHANTOM_MEMBRANE, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_серебро_iron_nugget", "[★] Серебро", Items.IRON_NUGGET, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_божье_касание_golden_pickaxe", "[★] Божье касание", Items.GOLDEN_PICKAXE, AutoBuyCategory.TOOLS, 100000L);
        add(items, "FunTime", "funtime_мощный_удар_golden_pickaxe", "[★] Мощный удар", Items.GOLDEN_PICKAXE, AutoBuyCategory.TOOLS, 100000L);
        add(items, "FunTime", "funtime_кирка_мега_бульдозер_netherite_pickaxe", "[★] Кирка мега-бульдозер", Items.NETHERITE_PICKAXE, AutoBuyCategory.TOOLS, 100000L);
        add(items, "FunTime", "funtime_дезориентация_ender_eye", "Дезориентация", Items.ENDER_EYE, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_явная_пыль_sugar", "Явная пыль", Items.SUGAR, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_пласт_dried_kelp", "Пласт", Items.DRIED_KELP, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_божья_аура_phantom_membrane", "Божья аура", Items.PHANTOM_MEMBRANE, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_снежок_заморозка_snowball", "Снежок заморозка", Items.SNOWBALL, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_трапка_netherite_scrap", "Трапка", Items.NETHERITE_SCRAP, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_блок_дамагер_jigsaw", "Блок дамагер", Items.JIGSAW, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_перегрузчик_чанков_5x5_structure_block", "Перегрузчик чанков [5x5]", Items.STRUCTURE_BLOCK, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_нерушимые_элитры_elytra", "Нерушимые элитры", Items.ELYTRA, AutoBuyCategory.ARMOR, 500000L);
        add(items, "FunTime", "funtime_пузыр_к_опыта_50_ур_experience_bottle", "Пузырёк опыта (50 ур.)", Items.EXPERIENCE_BOTTLE, AutoBuyCategory.EXPERIENCE, 2000L);
        add(items, "FunTime", "funtime_талисман_демона_totem_of_undying", "Талисман Демона", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_карателя_totem_of_undying", "Талисман Карателя", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_ирака_totem_of_undying", "Талисман Ирака", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_вихря_totem_of_undying", "Талисман Вихря", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_раздора_totem_of_undying", "Талисман Раздора", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_тирана_totem_of_undying", "Талисман Тирана", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_талисман_ярости_totem_of_undying", "Талисман Ярости", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 250000L);
        add(items, "FunTime", "funtime_драконий_скин_paper", "Драконий скин", Items.PAPER, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_незабвенный_скин_paper", "Незабвенный скин", Items.PAPER, AutoBuyCategory.MISC, 100000L);
        add(items, "FunTime", "funtime_шлем_крушителя_netherite_helmet", "Шлем Крушителя", Items.NETHERITE_HELMET, AutoBuyCategory.ARMOR, 500000L);
        add(items, "FunTime", "funtime_нагрудник_крушителя_netherite_chestplate", "Нагрудник Крушителя", Items.NETHERITE_CHESTPLATE, AutoBuyCategory.ARMOR, 500000L);
        add(items, "FunTime", "funtime_поножи_крушителя_netherite_leggings", "Поножи Крушителя", Items.NETHERITE_LEGGINGS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "FunTime", "funtime_ботинки_крушителя_netherite_boots", "Ботинки Крушителя", Items.NETHERITE_BOOTS, AutoBuyCategory.ARMOR, 500000L);
        add(items, "FunTime", "funtime_меч_крушителя_netherite_sword", "Меч Крушителя", Items.NETHERITE_SWORD, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "FunTime", "funtime_арбалет_крушителя_crossbow", "Арбалет Крушителя", Items.CROSSBOW, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "FunTime", "funtime_трезубец_крушителя_trident", "Трезубец Крушителя", Items.TRIDENT, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "FunTime", "funtime_лук_крушителя_bow", "Лук Крушителя", Items.BOW, AutoBuyCategory.WEAPONS, 500000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_обычный_campfire", "Сигнальный огонь (обычный)", Items.CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_богатый_campfire", "Сигнальный огонь (богатый)", Items.CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_случайный_campfire", "Сигнальный огонь (случайный)", Items.CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_сигнальный_огонь_мистический_soul_campfire", "Сигнальный огонь (мистический)", Items.SOUL_CAMPFIRE, AutoBuyCategory.BLOCKS, 100000L);
        add(items, "FunTime", "funtime_снотворное_splash_potion", "Снотворное", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_гнева_splash_potion", "Зелье Гнева", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_палладна_splash_potion", "Зелье Палладна", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_радиации_splash_potion", "Зелье Радиации", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_зелье_ассасина_splash_potion", "Зелье Ассасина", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_святая_вода_splash_potion", "Святая вода", Items.SPLASH_POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_несоздаваемое_зелье_potion", "Несоздаваемое зелье", Items.POTION, AutoBuyCategory.ALCHEMY, 45000L);
        add(items, "FunTime", "funtime_сфера_титана_player_head", "Сфера Титана", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_сатира_player_head", "Сфера Сатира", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_бестии_player_head", "Сфера Бестии", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "FunTime", "funtime_сфера_эрида_player_head", "Сфера Эрида", Items.PLAYER_HEAD, AutoBuyCategory.SPHERES, 250000L);
        add(items, "Universal", "universal_золотое_яблоко_golden_apple", "Золотое яблоко", Items.GOLDEN_APPLE, AutoBuyCategory.FOOD, 15000L);
        add(items, "Universal", "universal_зачарованное_золотое_яблоко_enchanted_golden_apple", "Зачарованное золотое яблоко", Items.ENCHANTED_GOLDEN_APPLE, AutoBuyCategory.FOOD, 150000L);
        add(items, "Universal", "universal_тотем_бессмертия_totem_of_undying", "Тотем бессмертия", Items.TOTEM_OF_UNDYING, AutoBuyCategory.MISC, 80000L);
        add(items, "Universal", "universal_пузыр_к_опыта_experience_bottle", "Пузырёк опыта", Items.EXPERIENCE_BOTTLE, AutoBuyCategory.EXPERIENCE, 2000L);
        add(items, "Universal", "universal_элитры_elytra", "Элитры", Items.ELYTRA, AutoBuyCategory.ARMOR, 500000L);
        add(items, "Universal", "universal_шалкер_все_shulker_box", "Шалкер (все)", Items.SHULKER_BOX, AutoBuyCategory.BLOCKS, 100000L);
        return items;
    }

    private static void add(List<AutoBuyItem> items, String server, String key, String display, Item item, AutoBuyCategory category, long price) {
        ItemStack stack = new ItemStack(item);
        stack.set(DataComponentTypes.CUSTOM_NAME, Text.literal(display));
        items.add(new AutoBuyItem(server, key, display, display, category, stack, price, true));
    }
}
